apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eventlistener
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eventlistener
    spec:      
      containers:
        - name: eventlistener
          image: shanepeckham/hackeventlistener:v2
          imagePullPolicy: Always
          env:
            -  name: "RABBITMQHOST"
               value: ""
            -  name: "PROCESSENDPOINT"
               value: "http://fulfillorder:8081/v1/order/"